### ISSUE TITLE
consider whether a carousel is appropriate 

### ISSUE THREAD

**Issue by amaiaita** [nhsengland/datascience#54]
After feedback from @warren-davies4 , determine whether we think a carousel is actually a good thing to have on the website. 

starting links: 
https://shouldiuseacarousel.com/
https://www.digital.ink/blog/website-carousel/
https://powerdigitalmarketing.com/blog/why-you-should-not-use-a-carousel-on-your-website/
https://www.zoomengage.com/blog/the-pros-and-cons-of-website-carousel-design-how-to-get-it-right
https://evielutions.com/the-pros-and-cons-to-carousels-in-web-design/
https://www.pragm.co/post/should-you-use-a-carousel-on-your-website

**Comment by warren-davies4** [comment]
I would display the projects in a grid layout (can be [non-uniform](https://www.erikjo.com/work), if you want to get funky).

If it's the visual appeal and interactivity that draws you to a carousel, you can add transitions to the boxes, such as have them fade in as they comes into view, or use hover effects, e.g., have then [zoom in slightly](https://coma.lv/projects/), or have a [brief description appear](https://unitaid.org/our-projects/#en).

**Comment by jrpearson-nhs** [comment]
Suggest to flatten caurosel and consider replacing the gerenated hospital image.
