### ISSUE TITLE
make all external links open in new tab

### ISSUE THREAD

**Issue by amaiaita** [nhsengland/datascience#87]
currently it takes you off the website - we want to keep people on!

**Comment by jenniferstruthers1-nhs** [comment]
I've started doing this for the RAP website/newsletter.
To save you any googling if you don't already know:
`[text](link){target="_blank"}`

And the {target="_blank"} is what automatically opens things in a new tab

**Comment by amaiaita** [comment]
incredible thanks so much @jenniferstruthers1-nhs
